/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Advertiser;

import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Exchange.Exchange;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import UserInterface.Exchange.ViewExchangeJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhinav
 */
public class AdvertiserWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AdvertiserEnterprise enterprise;
    private UserAccount account;
    private Network network;
    private Exchange exchange;
    /**
     * Creates new form AdvertiserWorkAreaJPanel
     */
    public AdvertiserWorkAreaJPanel(JPanel upc, Enterprise enterprise, UserAccount ua, Network network) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = (AdvertiserEnterprise) enterprise;
        this.account = ua;
        this.network = network;
        this.exchange = this.network.getExchange();
        
        hellojLabel.setText("Hi " + account.getPerson().getFirstName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignMarketingjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hellojLabel = new javax.swing.JLabel();
        rulejButton = new javax.swing.JButton();
        uploadjButton = new javax.swing.JButton();
        viewExchangejButton = new javax.swing.JButton();
        managefinancejButton = new javax.swing.JButton();

        assignMarketingjButton.setText("Assign Marketing Agency");
        assignMarketingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMarketingjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Work Area - Advertiser");

        rulejButton.setText("Manage Bidding Rules");
        rulejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulejButtonActionPerformed(evt);
            }
        });

        uploadjButton.setText("Upload Advertisements");
        uploadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadjButtonActionPerformed(evt);
            }
        });

        viewExchangejButton.setText("View Exchange");
        viewExchangejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewExchangejButtonActionPerformed(evt);
            }
        });

        managefinancejButton.setText("Manage Finance Account");
        managefinancejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managefinancejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hellojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assignMarketingjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rulejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uploadjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(viewExchangejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managefinancejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hellojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(viewExchangejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assignMarketingjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rulejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uploadjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(managefinancejButton)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignMarketingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMarketingjButtonActionPerformed
        
        userProcessContainer.add("Assign Marketing Agency", new AssignMarketingJPanel(userProcessContainer, enterprise, account, network));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_assignMarketingjButtonActionPerformed

    private void rulejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulejButtonActionPerformed
        
        userProcessContainer.add("Manage Bidding Rules", new ManageRulesJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_rulejButtonActionPerformed

    private void uploadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadjButtonActionPerformed
        
        userProcessContainer.add("Upload Advertisements", new UploadAdvertisementsJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_uploadjButtonActionPerformed

    private void viewExchangejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewExchangejButtonActionPerformed

        userProcessContainer.add("View Exchange", new ViewExchangeJPanel(userProcessContainer, exchange));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_viewExchangejButtonActionPerformed

    private void managefinancejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managefinancejButtonActionPerformed
        
        userProcessContainer.add("Manage Finance Account", new ManageFinanceAccountJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_managefinancejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignMarketingjButton;
    private javax.swing.JLabel hellojLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton managefinancejButton;
    private javax.swing.JButton rulejButton;
    private javax.swing.JButton uploadjButton;
    private javax.swing.JButton viewExchangejButton;
    // End of variables declaration//GEN-END:variables
}
