/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Advertiser;

import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MarketingAgencyEnterprise;
import Business.Network.Network;
import Business.WorkRequest.AdvertiserEnrollRequest;
import Business.WorkRequest.WorkRequest;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhinav
 */
public class AssignMarketingJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AdvertiserEnterprise enterprise;
    private UserAccount account;
    private Network network;
    /**
     * Creates new form AssignMarketingJPanel
     */
    public AssignMarketingJPanel(JPanel upc, Enterprise enterprise, UserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = (AdvertiserEnterprise) enterprise;
        this.account = account;
        this.network = network;
        
        populateTable();
        populateComboBox();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) requestjTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : enterprise.getWorkQueue().getWorkQueue())
        {
            Object[] row = new Object[4];
            row[0] = ((AdvertiserEnrollRequest)request).getMarketingEnterprise();
            row[1] = request.getReceiver();
            row[2] = request;
            row[3] = request.getComments();
            
            model.addRow(row);
            if(request.getStatus().equalsIgnoreCase("Approved"))
                submitjButton.setEnabled(false);
        }
    }
    
    private void populateComboBox()
    {
        marketingjComboBox.removeAllItems();
        for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList() )
        {
            if(e instanceof MarketingAgencyEnterprise)
            {
                marketingjComboBox.addItem(e);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        marketingjComboBox = new javax.swing.JComboBox();
        submitjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        requestjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marketing Agency", "Receiver", "Status", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestjTable);

        jLabel1.setText("Select Marketing Agency:");

        marketingjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitjButton.setText("Submit Request");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marketingjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(submitjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(marketingjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        
        MarketingAgencyEnterprise marketingEnterprise = (MarketingAgencyEnterprise) marketingjComboBox.getSelectedItem();
        AdvertiserEnrollRequest request = new AdvertiserEnrollRequest();
        request.setMarketingEnterprise(marketingEnterprise);
        request.setStatus("Request Sent");
        request.setSender(account);
        request.setAdvertiserEnterprise(enterprise);
        
        Enterprise isEnterprise = null;
        for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList())
        {
            if(e instanceof MarketingAgencyEnterprise)
            {
                if(((MarketingAgencyEnterprise)e).equals(marketingEnterprise))
                {
                    isEnterprise = e;
                }
            }
        }
        
        if(isEnterprise != null)
        {
            isEnterprise.getWorkQueue().getWorkQueue().add(request);
            enterprise.getWorkQueue().getWorkQueue().add(request);
        }
        
        populateTable();
    }//GEN-LAST:event_submitjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox marketingjComboBox;
    private javax.swing.JTable requestjTable;
    private javax.swing.JButton submitjButton;
    // End of variables declaration//GEN-END:variables
}
