/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Sales;

import Business.Enterprise.AdvertiserEnterprise;
import Business.Organization.SalesOrganization;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Abhinav
 */
public class ReviewSalesPerformanceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AdvertiserEnterprise enterprise;
    private SalesOrganization organization;
    /**
     * Creates new form ReviewSalesPerformanceJPanel
     */
    public ReviewSalesPerformanceJPanel(JPanel upc, AdvertiserEnterprise e, SalesOrganization org) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = e;
        this.organization = org;
        
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) reviewjTable.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[4];
        row[0] = enterprise.getConsumerClicks();
        row[1] = organization.getConsumerPurchases();
        row[2] = enterprise.getAccount().getTotalSpent();
        row[3] = organization.getProductCatalog().getTotalSales();
        
        model.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewjTable = new javax.swing.JTable();
        refreshjButton = new javax.swing.JButton();
        adVsSalejButton = new javax.swing.JButton();
        clickToPurchasejButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Review Performance");

        reviewjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Clicks on Ads", "Purchases", "Total Ad Expense", "Total Sales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reviewjTable);

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        adVsSalejButton.setText("Review Ads vs Sales Performance");
        adVsSalejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adVsSalejButtonActionPerformed(evt);
            }
        });

        clickToPurchasejButton.setText("Review Clicks vs Purchases Performance");
        clickToPurchasejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickToPurchasejButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(refreshjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clickToPurchasejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adVsSalejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adVsSalejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clickToPurchasejButton)
                .addGap(99, 99, 99)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed

        populateTable();
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void adVsSalejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adVsSalejButtonActionPerformed
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(enterprise.getAccount().getTotalSpent(), "Advertisement Expense vs Total Sales", "Ad Expenses");
        dataset.setValue(organization.getProductCatalog().getTotalSales(), "Advertisement Expense vs Total Sales", "Total Product Sales");
              
        JFreeChart chart = ChartFactory.createBarChart("Advertisement Expense vs Total Sales", "", "Amount", dataset, PlotOrientation.VERTICAL,false, true, false);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Advertisement Expense vs Total Sales", chart);
        frame.setVisible(true);
        frame.setSize(400, 400);
    }//GEN-LAST:event_adVsSalejButtonActionPerformed

    private void clickToPurchasejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickToPurchasejButtonActionPerformed
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(enterprise.getConsumerClicks(), "Consumer Clicks vs Purchases", "Consumer Clicks");
        dataset.setValue(organization.getConsumerPurchases(), "Consumer Clicks vs Purchases", "Consumer Purchases");
              
        JFreeChart chart = ChartFactory.createBarChart("Consumer Clicks vs Purchases", "", "Click Count", dataset, PlotOrientation.VERTICAL,false, true, false);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Consumer Clicks vs Purchases", chart);
        frame.setVisible(true);
        frame.setSize(400, 400);
    }//GEN-LAST:event_clickToPurchasejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adVsSalejButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton clickToPurchasejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JTable reviewjTable;
    // End of variables declaration//GEN-END:variables
}
