/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.MarketingAgency;

import Business.Enterprise.Enterprise;
import Business.Enterprise.MarketingAgencyEnterprise;
import Business.Exchange.Exchange;
import Business.Network.Network;
import Business.Organization.MarketingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Exchange.ViewExchangeJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhinav
 */
public class MarketingAgencyWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private MarketingAgencyEnterprise enterprise;
    private MarketingOrganization organization;
    private Network network;
    private Exchange exchange;
    /**
     * Creates new form MarketingAgencyWorkAreaJPanel
     */
    public MarketingAgencyWorkAreaJPanel(JPanel upc, UserAccount ua, Enterprise e, Organization org, Network network) {
        initComponents();
        this.userProcessContainer = upc;
        this.account = ua;
        this.enterprise = (MarketingAgencyEnterprise) e;
        this.organization = (MarketingOrganization) org;
        this.network = network;
        this.exchange = this.network.getExchange();
        
        hellojLabel.setText("Hi " + this.account.getPerson().getFirstName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hellojLabel = new javax.swing.JLabel();
        manageAdvertiserjButton = new javax.swing.JButton();
        advertiserListjButton = new javax.swing.JButton();
        viewExchangejButton = new javax.swing.JButton();
        paymentsjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Work Area - Marketing Agent");

        manageAdvertiserjButton.setText("Manage Advertiser Request");
        manageAdvertiserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdvertiserjButtonActionPerformed(evt);
            }
        });

        advertiserListjButton.setText("View Advertisers Enrolled");
        advertiserListjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertiserListjButtonActionPerformed(evt);
            }
        });

        viewExchangejButton.setText("View Exchange");
        viewExchangejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewExchangejButtonActionPerformed(evt);
            }
        });

        paymentsjButton.setText("View Incoming Payments");
        paymentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(hellojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageAdvertiserjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(advertiserListjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewExchangejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(hellojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(advertiserListjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageAdvertiserjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewExchangejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentsjButton)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdvertiserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdvertiserjButtonActionPerformed

        userProcessContainer.add("ManageAdvertiserRequest", new ManageAdvertiserRequestJPanel(userProcessContainer, enterprise, account));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageAdvertiserjButtonActionPerformed

    private void advertiserListjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertiserListjButtonActionPerformed
        
        userProcessContainer.add("Advertiser List", new ViewAdvertiserListJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_advertiserListjButtonActionPerformed

    private void viewExchangejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewExchangejButtonActionPerformed

        userProcessContainer.add("View Exchange", new ViewExchangeJPanel(userProcessContainer, exchange));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_viewExchangejButtonActionPerformed

    private void paymentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsjButtonActionPerformed
        
        userProcessContainer.add("View Incoming Payments", new ManagePaymentAndCommissionJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_paymentsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advertiserListjButton;
    private javax.swing.JLabel hellojLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAdvertiserjButton;
    private javax.swing.JButton paymentsjButton;
    private javax.swing.JButton viewExchangejButton;
    // End of variables declaration//GEN-END:variables
}
