/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Publisher;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Exchange.Exchange;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import UserInterface.Exchange.ViewExchangeJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhinav
 */
public class PublisherWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private PublisherEnterprise enterprise;
    private Network network;
    private Exchange exchange;
    /**
     * Creates new form PublisherWorkAreaJPanel
     */
    public PublisherWorkAreaJPanel(JPanel upc, UserAccount ua, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = upc;
        this.account = ua;
        this.enterprise = (PublisherEnterprise) enterprise;
        this.network = network;
        this.exchange = this.network.getExchange();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageAdSpacesjButton = new javax.swing.JButton();
        manageRulesjButton = new javax.swing.JButton();
        viewExchangejButton = new javax.swing.JButton();
        paymentsjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Work Area - Publisher");

        manageAdSpacesjButton.setText("Manage Ad Spaces");
        manageAdSpacesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdSpacesjButtonActionPerformed(evt);
            }
        });

        manageRulesjButton.setText("Manage Price Rules");
        manageRulesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRulesjButtonActionPerformed(evt);
            }
        });

        viewExchangejButton.setText("View Exchange");
        viewExchangejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewExchangejButtonActionPerformed(evt);
            }
        });

        paymentsjButton.setText("View Incoming Payments");
        paymentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(viewExchangejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageAdSpacesjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(paymentsjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageRulesjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(viewExchangejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageAdSpacesjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageRulesjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentsjButton)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdSpacesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdSpacesjButtonActionPerformed
        
        userProcessContainer.add("Manage Ad Spaces", new ManageAdSpacesJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageAdSpacesjButtonActionPerformed

    private void manageRulesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRulesjButtonActionPerformed
        
        userProcessContainer.add("Manage Ad Price Rules", new ManagePriceRulesJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageRulesjButtonActionPerformed

    private void viewExchangejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewExchangejButtonActionPerformed

        userProcessContainer.add("View Exchange", new ViewExchangeJPanel(userProcessContainer, exchange));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_viewExchangejButtonActionPerformed

    private void paymentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsjButtonActionPerformed
        
        userProcessContainer.add("View Incoming Payments", new IncomingPaymentsJPanel(userProcessContainer, enterprise));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_paymentsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAdSpacesjButton;
    private javax.swing.JButton manageRulesjButton;
    private javax.swing.JButton paymentsjButton;
    private javax.swing.JButton viewExchangejButton;
    // End of variables declaration//GEN-END:variables
}
